version: '3.8'

services:
  backend:
    build: ../backend
    env_file:
      - .env
    ports:
      - "8081:8081"
    depends_on:
      - redis
      - minio
    environment:
      - REDIS_ADDR=redis:6379
      - S3_ENDPOINT=minio:9000
      - S3_ACCESS_KEY=minioadmin
      - S3_SECRET_KEY=minioadmin
      - S3_BUCKET=images
      - API_KEYS=yourapikey123,anotherkey456
      # Add other needed env vars
    networks:
      - app-network

  frontend:
    build: ../frontend
    ports:
      - "8080:80"
    depends_on:
      - backend
    # no ports exposed, as nginx is the entrypoint
    networks:
      - app-network

  redis:
    image: redis:7
    ports:
      - "6379:6379"
    networks:
      - app-network

  minio:
    image: minio/minio:latest
    command: server /data
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    volumes:
      - minio-data:/data
    networks:
      - app-network

volumes:
  minio-data:

networks:
  app-network:
    driver: bridge